library(dplyr)
library(ggplot2)
library(future)
library(ranger)
library(patchwork)

# Required objects:
# - nested_rep_tbl: generated by 05a_ML_reg_train.R
# - build_X_for_shap(): defined in ML_reg_func.R
# - T1label_bio: variable label list defined in the main analysis environment (00_comparison_tables)
# - SuppleFigS11A: generated by 05c_ML_reg_plot2.R
# - .seed_shap_reg: random seed for SHAP calculations

# Choose a representative outer fold within a given repeat (closest to median R2)
choose_fold_for_shap <- function(rep_obj, metric = "R2") {
  # rep_obj is one element of per_repeat (returned by nested_fit_regression)
  stopifnot(!is.null(rep_obj$fold_stats))
  fs <- rep_obj$fold_stats # has columns: outer_fold, RMSE, MAE, R2, ...
  med <- stats::median(fs[[metric]], na.rm = TRUE)
  fs$dist <- abs(fs[[metric]] - med)
  as.integer(fs$outer_fold[which.min(fs$dist)])
}

# Compute SHAP for a single representative fold (with optional subsampling)
# Align columns to 'features' (add missing dummies as 0 and reorder)
align_to_features <- function(X, features) {
  miss <- setdiff(features, colnames(X))
  if (length(miss)) X[miss] <- 0
  X[, features, drop = FALSE]
}

# Coerce xgb TreeSHAP output to a matrix even for a single row
coerce_shap_matrix_xgb <- function(shap_raw, nrow_expected, ncol_expected) {
  if (is.null(dim(shap_raw))) {
    shap_raw <- matrix(shap_raw, nrow = nrow_expected, ncol = ncol_expected + 1, byrow = TRUE)
  }
  shap_raw
}


compute_shap_single_fold <- function(rep_obj, fold_id,
                                     seed = 12345, nsim = 30, bg_n = 50, test_subsample = 200) {
  fit_k <- rep_obj$fit_list[[fold_id]]
  te_k  <- rep_obj$test_list[[fold_id]]
  stopifnot(!is.null(fit_k$model))
  
  # Build test design with the same dummy/scaling as the training fold
  Xk <- build_X_for_shap(fit_k, te_k)
  Xk <- align_to_features(Xk, fit_k$features)
  
  # Optional subsample of test rows (for faster beeswarm)
  if (!is.null(test_subsample) && nrow(Xk) > test_subsample) {
    set.seed(seed + fold_id)
    idx <- sample.int(nrow(Xk), test_subsample)
    Xk <- Xk[idx, , drop = FALSE]
  }
  
  # Background from training design matrix (already post-scaled); small fixed subsample
  bg <- fit_k$train_X_for_shap
  if (is.null(bg)) bg <- Xk
  if (nrow(bg) > bg_n) {
    set.seed(seed + 1000L + fold_id)
    bg <- bg[sample.int(nrow(bg), bg_n), , drop = FALSE]
  }
  bg <- align_to_features(bg, fit_k$features)
  
  # Prediction wrapper (caret/xgboost/ranger/others) - FIXED
  predfun <- function(object, newdata) {
    if (inherits(object, "xgb.Booster")) {
      as.numeric(predict(object, xgboost::xgb.DMatrix(as.matrix(newdata))))
    } else if (inherits(object, "train")) {
      # caret train object
      # Check if it's ranger model
      if (!is.null(object$modelInfo$library) && "ranger" %in% object$modelInfo$library) {
        # ranger model inside caret train object
        as.numeric(predict(object$finalModel, data = newdata)$predictions)
      } else {
        # other caret models
        as.numeric(predict(object, newdata = newdata))
      }
    } else {
      as.numeric(predict(object, newdata = newdata, type = "response"))
    }
  }
  
  # Compute SHAP: TreeSHAP for xgb; fastshap otherwise
  if (inherits(fit_k$model, "xgb.Booster")) {
    dX <- xgboost::xgb.DMatrix(as.matrix(Xk))
    colnames(dX) <- colnames(Xk)
    shap_raw <- predict(fit_k$model, dX, predcontrib = TRUE)
    shap_df  <- as.data.frame(shap_raw)
    # Drop BIAS safely (prefer name; else assume last col)
    bias_cols <- grep("BIAS", colnames(shap_df), ignore.case = TRUE)
    if (length(bias_cols)) {
      shap_df <- shap_df[, -bias_cols, drop = FALSE]
    } else if (ncol(shap_df) == ncol(Xk) + 1) {
      shap_df <- shap_df[, seq_len(ncol(Xk)), drop = FALSE]
    }
    colnames(shap_df) <- colnames(Xk)
  } else {
    set.seed(seed + fold_id)
    shap_df <- fastshap::explain(
      object       = fit_k$model,
      X            = bg,          # background (training subsample) 
      pred_wrapper = predfun,
      nsim         = nsim,
      newdata      = Xk           # instances to explain (test fold, subsampled)
    )
    shap_df <- as.data.frame(shap_df)
    shap_df <- shap_df[, colnames(Xk), drop = FALSE]
  }
  
  # Long format + within-feature rank for stable coloring
  long <- shap_df %>%
    dplyr::mutate(obs = dplyr::row_number(), outer_fold = fold_id) %>%
    tidyr::pivot_longer(-c(obs, outer_fold), names_to = "feature", values_to = "phi") %>%
    dplyr::left_join(
      Xk %>%
        dplyr::mutate(obs = dplyr::row_number(), outer_fold = fold_id) %>%
        tidyr::pivot_longer(-c(obs, outer_fold), names_to = "feature", values_to = "feature_value"),
      by = c("obs", "outer_fold", "feature")
    ) %>%
    dplyr::group_by(feature) %>%
    dplyr::mutate(
      n_levels = dplyr::n_distinct(feature_value),
      stdfvalue = dplyr::if_else(
        n_levels <= 2,
        as.numeric(feature_value > mean(feature_value, na.rm = TRUE)),   # binary mapping
        (rank(feature_value, ties.method = "average") - 1) / (dplyr::n() - 1) # 0..1
      )
    ) %>%
    dplyr::ungroup()
  
  long
}



# Plot SHAP beeswarm for a single representative repeat × fold ----------------

# --- compute_mean_shap_ranking with lightweight progress + error swallowing ---

compute_mean_shap_ranking <- function(nested_rep_tbl, method,
                                      repeats_to_use = NULL, seed = 12345,
                                      nsim = 20, bg_n = 50, test_subsample = 50, topk = 30) {
  if (method %in% c("glm","lm")) stop("GLM does not need SHAP.")
  obj <- nested_rep_tbl %>% dplyr::filter(model == method)
  prs <- obj$per_repeat[[1]]
  R <- length(prs)
  reps <- if (is.null(repeats_to_use)) seq_len(R) else intersect(repeats_to_use, seq_len(R))
  
  # Pre-compute total tasks for progress ratio
  Ks <- vapply(reps, function(r) length(prs[[r]]$fit_list), integer(1))
  total_tasks <- sum(Ks)
  cat(sprintf(">> Mean |SHAP| ranking for %s | repeats=%d | total folds=%d (nsim=%d, bg_n=%d, test_subsample=%d)\n",
              method, length(reps), total_tasks, nsim, bg_n, test_subsample))
  
  all_chunks <- list()
  task_counter <- 0L
  
  for (r in reps) {
    rep_obj <- prs[[r]]
    K <- length(rep_obj$fit_list)
    for (k in seq_len(K)) {
      task_counter <- task_counter + 1L
      pct <- floor(100 * (task_counter - 1) / max(1L, total_tasks))
      cat(sprintf("\r   - [%d/%d] repeat=%d fold=%d ... %3d%%",
                  task_counter, total_tasks, r, k, pct)); utils::flush.console()
      
      # Protect each (repeat, fold); continue on failure
      chunk <- tryCatch(
        {
          compute_shap_single_fold(
            rep_obj, k,
            seed = seed + 1000L * r + k,
            nsim = nsim, bg_n = bg_n, test_subsample = test_subsample
          )
        },
        error = function(e) {
          cat(sprintf("\n!! SHAP failed (repeat=%d, fold=%d): %s\n", r, k, conditionMessage(e)))
          NULL
        }
      )
      if (!is.null(chunk)) {
        chunk$repeat_id <- r
        all_chunks[[length(all_chunks) + 1L]] <- chunk
      }
    }
  }
  cat(sprintf("\r   - done %d/%d ... 100%%\n", total_tasks, total_tasks)); utils::flush.console()
  
  if (length(all_chunks) == 0L) {
    cat("!! No SHAP chunks were produced (all tasks failed)\n")
    return(tibble::tibble(feature = character(0), mean_abs_shap = numeric(0)))
  }
  
  all_shap <- dplyr::bind_rows(all_chunks)
  
  rank_tbl <- all_shap %>%
    dplyr::group_by(feature) %>%
    dplyr::summarise(mean_abs_shap = mean(abs(phi), na.rm = TRUE), .groups = "drop") %>%
    dplyr::arrange(dplyr::desc(mean_abs_shap)) %>%
    dplyr::slice_head(n = topk)
  
  rank_tbl
}




# Load nested repeat results ----------------------------

# trained models and results from repeated nested CV (from 05a_ML_reg_train.R)

#trained_results <- readRDS("output/XXX.rds")
#nested_rep_tbl <- trained_results$ml_results
#glm_subset_results <- trained_results$glm_results
#metadata <- trained_results$metadata


# Mean |SHAP| ranking across repeats/folds (lightweight TEST) -------------------

rank_rf  <- compute_mean_shap_ranking(nested_rep_tbl, "rf",  repeats_to_use = 1:10, seed = .seed_shap_reg,
                                      nsim = 100, bg_n = 100, test_subsample = NULL, topk = 30) %>% mutate(model = "rf")

rank_xgb <- compute_mean_shap_ranking(nested_rep_tbl, "xgb", repeats_to_use = 1:10, seed = .seed_shap_reg,
                                      nsim = 100, bg_n = 100, test_subsample = NULL, topk = 30) %>% mutate(model = "xgb")

rank_knn  <- compute_mean_shap_ranking(nested_rep_tbl, "knn",  repeats_to_use = 1:10, seed = .seed_shap_reg,
                                       nsim = 100, bg_n = 100, test_subsample = NULL, topk = 30) %>% mutate(model = "knn")

rank_svm  <- compute_mean_shap_ranking(nested_rep_tbl, "svmRadial",  repeats_to_use = 1:10, seed = .seed_shap_reg,
                                       nsim = 100, bg_n = 100, test_subsample = NULL, topk = 30) %>% mutate(model = "svmRadial")


# Combine all rankings --------------------------------------

ml_colors <- c(
  "RF"        = "#C96A1B",  # dark orange
  "XGB"       = "#E28E2C",  # mid orange
  "SVM"       = "#3F6F63",  # darker green-gray
  "KNN"       = "#7FA69A",  # mid green-gray
  "GLM"       = "#4C6FA1"  # muted blue
  #"NfL alone" = "gray25",
)


variable_labels <- unlist(T1label_bio)

# --- Normalization and overall ordering ---
rank_all <- dplyr::bind_rows(rank_rf, rank_xgb, rank_knn, rank_svm) %>%
  dplyr::mutate(mean_abs_shap_raw = mean_abs_shap) %>%
  # Within-model normalization
  dplyr::group_by(model) %>%
  dplyr::mutate(mean_abs_shap_norm = mean_abs_shap / sum(mean_abs_shap, na.rm = TRUE)) %>%
  dplyr::ungroup() %>%
  # Overall ordering by mean normalized SHAP
  dplyr::group_by(feature) %>%
  dplyr::mutate(all_mean_abs_shap = mean(mean_abs_shap_norm, na.rm = TRUE)) %>%
  dplyr::ungroup() %>%
  # Model factor - normalize svmRadial to svm
  dplyr::mutate(
    model = tolower(as.character(model)),
    model = ifelse(model == "svmradial", "svm", model),
    model = factor(model, levels = c("knn", "svm", "xgb", "rf")),
    model = dplyr::recode(model,
                          "knn" = "KNN",
                          "svm" = "SVM",
                          "rf"  = "RF",
                          "xgb" = "XGB")
  ) %>%
  dplyr::arrange(dplyr::desc(all_mean_abs_shap))

rank_all


# arranged for RF ranking --------------------------------------

rank_all_rf <- rank_all %>%
  dplyr::filter(model == "RF") %>%
  dplyr::arrange(dplyr::desc(mean_abs_shap_norm)) %>%
  dplyr::mutate(rank_rf = dplyr::row_number())

rank_all <- rank_all %>%
  dplyr::left_join(
    rank_all_rf %>%
      dplyr::select(feature, rank_rf),
    by = "feature"
  ) %>%
  dplyr::arrange(desc(rank_rf)) %>%
  dplyr::mutate(feature = factor(feature, levels = unique(feature)))

rank_all

## Plot mean |SHAP| ranking across models ---------------

SuppleFig_SHAP_slope <- ggplot(rank_all, #%>% filter(model %in% c("RF","XGB")), 
                               aes(x = feature, 
                                   y = mean_abs_shap_norm, fill = model)) +
  geom_col(position = "dodge", alpha = 0.8) +
  coord_flip() +
  # Apply variable labels
  scale_x_discrete(labels = function(x) ifelse(x %in% names(variable_labels), variable_labels[x], x)) +
  # Apply color mapping
  scale_fill_manual(
    values = ml_colors,
    breaks = c("KNN", "SVM", 
               "XGB", "RF"),  # control legend order
    labels = c("KNN", "SVM", 
               "XGB", "RF")
  ) +
  labs(
    title = "(B) Feature importance for ALSFRS-R slope prediction",
    subtitle = "Normalised SHAP values across nested cross-validation repeats and folds",
    x = NULL, 
    y = "Normalised |SHAP| (relative contribution)",
    fill = "Model",
  ) +
  theme_bw(base_size = 16) +
  theme(legend.position = "bottom",
        plot.title = element_text(size = 18, face = "bold"),
        plot.subtitle = element_text(size = 14))

SuppleFig_SHAP_slope

SuppleFigS11B <- SuppleFig_SHAP_slope


# 🔍 SuppleFig S11 -----------------------------------------------------------

SuppleFig11 <-  SuppleFigS11A|SuppleFigS11B
SuppleFig11
