library(dplyr)
library(tidyr)
library(ggplot2)
library(cowplot)

# ────────────────────────────────────────────────────────────────────────
# Borm-style covariate-adjusted sample-size calculation
# ────────────────────────────────────────────────────────────────────────
# Requires glm_subset_results generated by the upstream GLM subset analysis script.
# R2_cv is used as an approximate variance-reduction factor in this Borm-style sample-size calculation.

# Configuration -------------------------------------------

config_borm_ancova <- list(
  sd_base = 6.0,  # Reference SD from the edaravone trial (Lancet Neurol 2017)
  delta_seq = seq(2.0, 4.0, by = 0.1),
  delta_reference = 3.0,
  delta_bars = c(2.4, 3.0, 3.6),
  alpha = 0.05,
  power = 0.80
)

delta_bar_labels <- setNames(
  paste0(
    config_borm_ancova$delta_bars, " pts (",
    sprintf("%.1f", config_borm_ancova$delta_bars / 6), "/month)"
  ),
  config_borm_ancova$delta_bars
)

sd_base_borm <- config_borm_ancova$sd_base

map_model_name_borm <- function(x) {
  dplyr::case_when(
    x == "Crude" ~ "Unadjusted",
    x == "Core3" ~ "Core 3",
    x == "Core3_NfL" ~ "Core 3 + NfL",
    x == "Core0_NfL" ~ "NfL",
    grepl("^Core3_NfL_.*x.*Ab42_40", x) ~ "Core 3 + NfL × Aβ42/40",
    TRUE ~ x
  )
}

# Select models ---------------------------------------------

models_to_select_borm <- c(
  "Crude",
  "Core0_NfL",
  "Core3",
  "Core3_NfL",
  "Core3_NfL_Ab42_40_csf_bridged_xAb42_40_csf_bridged"
)


models_borm_selected <- glm_subset_results$nested %>%
  dplyr::filter(model %in% models_to_select_borm) %>%
  dplyr::select(model, rep_stats) %>%
  tidyr::unnest(rep_stats) %>%
  dplyr::group_by(model) %>%
  dplyr::summarise(
    R2_cv = mean(R2cor, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  dplyr::bind_rows(tibble::tibble(model = "Crude", R2_cv = 0)) %>%
  dplyr::distinct(model, .keep_all = TRUE) %>%
  dplyr::mutate(
    R2_cv = dplyr::if_else(model == "Crude", 0, R2_cv),
    model_clean = map_model_name_borm(model)
  )

print(models_borm_selected)


# Sample-size calculation ---------------------------------------------

calc_n_borm_ancova <- function(delta_seq, sd_base, r2_cv,
                               alpha = 0.05, power = 0.80) {
  
  effect_size <- delta_seq / sd_base
  
  n_per_group_crude <- purrr::map_dbl(
    effect_size,
    ~ pwr::pwr.t.test(
      d = .x,
      sig.level = alpha,
      power = power,
      type = "two.sample",
      alternative = "two.sided"
    )$n
  )

  # Approximate illustrative calculation 
  n_total_crude <- ceiling(n_per_group_crude * 2)
  n_total_adjusted <- ceiling(n_total_crude * (1 - r2_cv))
  
  n_per_group_adjusted <- n_total_adjusted / 2
  
  if (r2_cv > 0) {
    # Conservative small-sample safeguard; not triggered in the plotted range.
    n_total_adjusted <- ifelse(
      n_per_group_adjusted < 25,
      n_total_adjusted + 2,
      n_total_adjusted
    )
  }
  
  reduction_pct <- 100 * (n_total_crude - n_total_adjusted) / n_total_crude
  reduction_pct <- pmax(0, reduction_pct)
  
  tibble::tibble(
    delta = delta_seq,
    effect_size = effect_size,
    n_per_group_crude = n_per_group_crude,
    n_total_crude = n_total_crude,
    n_total_adjusted = n_total_adjusted,
    reduction_pct = reduction_pct,
    r2_used = r2_cv
  )
}

results_borm_ancova <- models_borm_selected %>%
  tidyr::crossing(delta = config_borm_ancova$delta_seq) %>%
  dplyr::group_by(model, model_clean, R2_cv) %>%
  dplyr::reframe(
    calc_n_borm_ancova(
      delta_seq = delta,
      sd_base = sd_base_borm,
      r2_cv = R2_cv[1],
      alpha = config_borm_ancova$alpha,
      power = config_borm_ancova$power
    )
  )

model_order_borm <- models_borm_selected %>%
  dplyr::arrange(desc(model == "Crude"), R2_cv) %>%
  dplyr::pull(model_clean) %>%
  unique()

results_borm_ancova <- results_borm_ancova %>%
  dplyr::mutate(model_clean = factor(model_clean, levels = model_order_borm))


# Line plot ------------------------------------------------------

p_line_borm_ancova <- ggplot(
  results_borm_ancova,
  aes(x = delta, y = n_total_adjusted, color = model_clean)
) +
  geom_smooth(se = FALSE, method = "loess", span = 0.4, linewidth = 1.2) +
  geom_vline(
    xintercept = config_borm_ancova$delta_reference,
    linetype = "dotted",
    alpha = 0.5,
    color = "gray10"
  ) +
  coord_cartesian(xlim = c(2.2, 3.8), ylim = c(0, NA)) +
  labs(
    title = "Sample size requirements under covariate adjustment strategies",
    x = "Expected treatment effect (ΔALSFRS-R /24 weeks)",
    y = "Required total sample size",
    color = "Adjustment model"
  ) +
  xlim(2.2, 3.8) +
  theme_classic(base_size = 18) +
  theme(
    legend.position = c(0.98, 0.99),
    legend.text = element_text(size = 14),
    legend.justification = c("right", "top"),
    legend.title = element_text(size = 16),
    legend.background = element_rect(fill = "white", colour = NA),
    legend.box.background = element_rect(
      fill = "white",
      colour = "gray50",
      linewidth = 0.6
    ),
    plot.title = element_text(size = 20, face = "bold"),
    plot.subtitle = element_text(size = 16),
    axis.title = element_text(size = 17),
    axis.text = element_text(size = 16),
    axis.title.x = element_text(
      margin = ggplot2::margin(t = 10, b = 2)
    )
  ) +
  guides(color = guide_legend(ncol = 2)) +
  scale_color_manual(
    values = c("gray70", "#E3A55D", "#8FC7B6", "#5FAE9C", "#2F7F6F")
  )

p_line_borm_ancova


# Bar plot ------------------------------------------------------

results_bar_borm_ancova <- results_borm_ancova %>%
  dplyr::filter(delta %in% config_borm_ancova$delta_bars) %>%
  dplyr::mutate(
    Delta_fac = factor(
      delta,
      levels = config_borm_ancova$delta_bars,
      labels = unname(delta_bar_labels[as.character(config_borm_ancova$delta_bars)])
    )
  )

ref_tbl_borm_ancova <- results_bar_borm_ancova %>%
  dplyr::filter(model == "Crude") %>%
  dplyr::select(delta, n_total_ref = n_total_adjusted)

results_bar_borm_ancova <- results_bar_borm_ancova %>%
  dplyr::left_join(ref_tbl_borm_ancova, by = "delta") %>%
  dplyr::mutate(
    pct_reduction_vs_crude = 100 * (n_total_ref - n_total_adjusted) / n_total_ref,
    pct_reduction_vs_crude = ifelse(pct_reduction_vs_crude < 0, 0, pct_reduction_vs_crude),
    label_pct = ifelse(model == "Crude", "", sprintf("-%.0f%%", pct_reduction_vs_crude))
  ) %>%
  dplyr::group_by(Delta_fac) %>%
  dplyr::mutate(
    model_clean_ord = forcats::fct_reorder(
      .f = model_clean,
      .x = n_total_adjusted,
      .desc = TRUE
    )
  ) %>%
  dplyr::ungroup()

p_bar_borm_ancova <- ggplot(
  results_bar_borm_ancova,
  aes(x = model_clean_ord, y = n_total_adjusted, fill = model_clean)
) +
  geom_col(width = 0.7, colour = "gray70", linewidth = 0.125) +
  geom_text(
    aes(label = label_pct),
    vjust = -1,
    hjust = 0.3,
    angle = 15,
    size = 4
  ) +
  labs(
    x = NULL,
    y = "Required total sample size",
    fill = "Adjustment model"
  ) +
  theme_bw(base_size = 18) +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 20, face = "bold"),
    plot.subtitle = element_text(size = 14),
    axis.title = element_text(size = 16),
    axis.text.y = element_text(size = 14),
    axis.text.x = element_text(
      angle = 30,
      hjust = 1,
      vjust = 1.1,
      size = 14,
      margin = ggplot2::margin(t = 8, b = 0)
    )
  ) +
  guides(fill = guide_legend(ncol = 2)) +
  facet_wrap(~ Delta_fac, nrow = 1, scales = "free_x") +
  coord_cartesian(
    ylim = c(0, max(results_bar_borm_ancova$n_total_adjusted) * 1.15)
  ) +
  scale_fill_manual(
    values = c("gray70", "#E3A55D", "#8FC7B6", "#5FAE9C", "#2F7F6F")
  )

p_bar_borm_ancova

# 📊 Figure 6B --------------------------------------------

Fig6B <- cowplot::ggdraw() +
  cowplot::draw_plot(
    p_line_borm_ancova,
    x = 0,
    y = 0,
    width = 0.5,
    height = 1
  ) +
  cowplot::draw_plot(
    p_bar_borm_ancova,
    x = 0.5,
    y = 0,
    width = 0.5,
    height = 0.925
  )

Fig6B


# Comparison table ---------------------------------------------

comparison_tbl_borm_ancova <- results_borm_ancova %>%
  dplyr::filter(delta %in% config_borm_ancova$delta_bars) %>%
  dplyr::select(model, model_clean, delta, n_total_adjusted, reduction_pct) %>%
  tidyr::pivot_wider(
    names_from = delta,
    values_from = n_total_adjusted,
    names_prefix = "n_Delta"
  ) %>%
  dplyr::left_join(
    models_borm_selected %>% dplyr::select(model, R2_cv),
    by = "model"
  ) %>%
  dplyr::select(model_clean, R2_cv, everything(), -model) %>%
  dplyr::arrange(desc(R2_cv))

print("Comparison table (sample size at key Delta values):")
print(comparison_tbl_borm_ancova, n = Inf)


# Sanity check ------------------------------------------------------------

check_r2_definition <- glm_subset_results$nested %>%
  dplyr::filter(model %in% models_to_select_borm) %>%
  dplyr::select(model, rep_stats) %>%
  tidyr::unnest(rep_stats) %>%
  dplyr::group_by(model) %>%
  dplyr::summarise(
    R2_cor = mean(R2cor, na.rm = TRUE),
    R2_sse = mean(R2, na.rm = TRUE),
    difference = R2_cor - R2_sse,
    .groups = "drop"
  )

# very nearly identical: difference < 0.01 for all
print(check_r2_definition)
